# Generated by Django 3.0.3 on 2020-10-19 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(choices=[(1, 'Simples'), (2, 'Duplo'), (3, 'Terço'), (4, 'Quarto'), (5, 'Quinto'), (6, 'Sexto')])),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.Disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turma.Turma')),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'db_table': 'Card',
            },
        ),
    ]
